server {
        listen 127.0.0.1:80;
        server_name 7k6tvoewrqcblqnwivxzqb2rekgp2jsew5kbwvlspiglelxuk5ofhbid.onion;

        root /var/www/onion;
        index index.html index.htm;

        location / {
                try_files $uri $uri/ =404;
        }
}